### ISSUE TITLE
Plugins without audio channels are not listed

### ISSUE THREAD

**Issue by Houston4444** [Stazed/non-mixer-xt#1]
Hi, thanks for this repo, it seems to be interesting.
I tag @jean-emmanuel , I think he would be happy to know the existence of this fork.

Plugins without audio channels are not listed, it is probably intentional because it's an audio mixer, that is just to be sure. I search a LV2 plugin host capable to make works plugins with many MIDI inputs.

**Comment by Stazed** [comment]
Yeah, the mixer requires at least one audio out for the default gain module. If you had one audio out, it might work with many MIDI inputs.... maybe. It is written to handle multiple MIDI ports but I have not found a plugin to test it with.

**Comment by Houston4444** [comment]
I achieve to make it works, I needed to add one audio input and one audio output to my plugin with 2 Midi inputs and one midi output, it works well, nice !
Thus, It's quite a shame to have a so nice and light LV2 Host (with a nice OSC support), with no support of simple MIDI utilities without audio.

Thanks a lot.

**Comment by Stazed** [comment]
Good to hear that multiple MIDI ports work! I looked at support for MIDI only a while back and it seemed like it would be a big hassle as everything using the mixer chain is designed for audio connections. I will take a look at this again after I finish testing and put out the official first release.

BTW, your plugin would not need the audio input, it would just need to be inserted like a zero input synth... directly after the jack module.

**Comment by Stazed** [comment]
After looking at this, it seems that the restriction on MIDI only was invalid. The code implemented for use with zero input synths will also work with MIDI only. I just needed to allow MIDI only plugins to be listed in the plugin chooser. The help has been updated to explain special insertion requirements and some limitations.

The fix for this is in the wip branch.
