### ISSUE TITLE
Documentation for OSC?

### ISSUE THREAD

**Issue by Stazed** [Stazed/non-mixer-xt#10]
Hey @jean-emmanuel,
Let me know if/when you are done with your changes and I will push out the next release.

In addition, if you want to add any documentation/links to demonstrate the usage please paste it here and I will add it to the README and/or help for the release.

Thanks.

**Comment by jean-emmanuel** [comment]
For now I think non-mixer-xt does everything I need to be able to replace non-mixer in our live setup (haven't done it yet though). I'll try to write some basic examples soon.

**Comment by jean-emmanuel** [comment]
Here is a first draft :https://gist.github.com/jean-emmanuel/2db8459e3a1473c8891cfca50e7e85bc

**Comment by Stazed** [comment]
Excellent! Nicely presented and in depth!

**Comment by Stazed** [comment]
Thanks!

**Comment by jean-emmanuel** [comment]
My pleasure !  Looks like I forgot to write the `(OSC.md)` part of the link in the readme
