### ISSUE TITLE
copyright missing

### ISSUE THREAD

**Issue by trebmuh** [Stazed/non-mixer-xt#18]
```
non-mixer-xt
The Non-Mixer-XT 1.0.0  -- Copyright (c) 2008-2013 Jonathan Moore Liles
...
...
```
Would be nice to add yourself.

**Comment by Stazed** [comment]
This actually made me laugh! Thank you!
As for putting my name in the copyright, it seems contradictory to the whole open source idea, and I suspect that it is done by the professionals so they can show it on their resume.

For anyone who wants to know, I am a self taught, part-time, hobby programmer with no aspirations of becoming a professional. My contributions to open source come from my desire to build a home recording studio out old abandoned projects that I can maintain myself :).

Nope, not gonna do this...

**Comment by trebmuh** [comment]
I don't get why it made you laugh because you already add yourself in the GUI credits:
![non-mixer-qt](https://user-images.githubusercontent.com/8705846/226214541-b54be02f-7269-4565-918c-af52bdf5789b.png)
then I don't get why you would add yourself in one place, but think it's contradictory to add yourself in another place.

Do I miss something?

**Comment by Stazed** [comment]
Don't take it personally, just my twisted sense of humor.
I am not an attorney, but googling the definition of "copyright" generally is used to give the originator "exclusive" ownership. Which seems to contradict the open source idea. But of course in every file, is the GNU license which gives away the exclusive ownership.

Anyway, I put my alias in the credits, but I leave the "Copyright" as is since it is not important to me, but might be important to the original creator of the project.

**Comment by trebmuh** [comment]
As I understand it (I'm not a lawyer), this is because one have copyright ownership (paternity) that he's able  to make it available to other. This is what is known as "copyleft" (see https://en.wikipedia.org/wiki/Copyleft ).

Anyway, I don't want to seem pushy nor nitpicking here. Feel free to discard my suggestion, and more important to my eyes, thanks for maintaining and developing non-mixer ! It was a great project by Jonathan, and a lot of people have been sad that he left the web and the non-* realm because of personal issue with other people. So, once again, thanks for taking care of this little gem which is non-mixer.

**Comment by Stazed** [comment]
Just pushed an update to the Copyright on the wip branch. 
I am so burnt out on this project to the point of just being silly...
