### ISSUE TITLE
Program crashes after trying to add a strip

### ISSUE THREAD

**Issue by BMuXBeats** [Stazed/non-mixer-xt#21]
First I've cloned the actual package fro github. Then I've cathced the submodules, as you described.  
After all that, I've installed it with _makepkg -si_ in the arch-subdirectory.  
  
The program started normally.  
After creating a new project, as you described, I've tried to add a new strip. The program crashed immediately.  
 

> **\[username@desktop-username test-projects\]$** non-mixer-xt   
> The Non-Mixer-XT 1.0.6   
> Copyright (c) 2008-2021 Jonathan Moore Liles   
> Copyright (c) 2022-2023 Stazed   
> \[**non-mixer-xt**\] **Waiting for plugins...**   
> WARNING: Plugin is not RT capable   
> WARNING: Plugin 1192 not added   
> WARNING: Plugin is not RT capable   
> WARNING: Plugin 1215 not added   
> WARNING: Plugin is not RT capable   
> WARNING: Plugin 1211 not added   
> WARNING: Plugin is not RT capable   
> WARNING: Plugin 1402 not added   
> WARNING: Plugin is not RT capable   
> WARNING: Plugin 1202 not added   
> WARNING: Plugin is not RT capable   
> WARNING: Plugin 1210 not added   
> WARNING: Plugin is not RT capable   
> WARNING: Plugin 1199 not added   
> WARNING: Plugin is not RT capable   
> WARNING: Plugin 1201 not added   
> WARNING: Could not open path /usr/local/lib/ladspa/   
> 172 plugins found in 127 libraries   
> WARNING: LADSPA\_RDF\_PATH environment variable not set   
>         Assuming /usr/share/ladspa/rdf:/usr/local/share/ladspa/rdf   
> WARNING: Could not open path /usr/local/share/ladspa/rdf/   
> lilv\_world\_add\_plugin(): warning: Duplicate plugin \<https://github.com/werman/noise-suppression-for-voice\>   
> lilv\_world\_add\_plugin(): warning: ... found in file:///home/username/.lv2/rnnoise\_mono.lv2/   
> lilv\_world\_add\_plugin(): warning: ... and      file:///home/username/.lv2/rnnoise\_stereo.lv2/ (ignored)   
> lilv\_world\_load\_bundle(): warning: Replacing version 0.0 of \<https://github.com/HiFi-LoFi/KlangFalter\> from \<file:///home/username/.lv2/KlangFalter.lv2/>   
> lilv\_world\_load\_bundle(): note: New version 3.9 found in \<file:///usr/lib/lv2/KlangFalter.lv2/>   
> OSC=osc.udp://desktop-username:10059/   
> \[**non-mixer-xt**\] **Info: created by = The Non-Mixer-XT 1.0.6**   
> \[**non-mixer-xt**\] **Info: created on = Wed Nov 22 16:50:45 2023**   
> \[**non-mixer-xt**\] **Info: version = 1**   
> \[**non-mixer-xt**\] **Loaded project "/home/username/tmp/test-projects/tst"**   
> \[**non-mixer-xt**\] **Created project "/home/username/tmp/test-projects/tst" from template "(null)"**   
> /usr/include/c++/13.2.1/bits/stl\_vector.h:1125: std::vector\<\_Tp, \_Alloc>::reference std::vector\<\_Tp, \_Alloc>::operator\[\](size\_type) \[with \_Tp = Module::Port; \_Alloc = std::allocator\<Modu  
> le::Port>; reference = Module::Port&; size\_type = long unsigned int\]: Assertion '\_\_n \< this->size()' failed.   
> Abgebrochen (Speicherabzug geschrieben) 

Program-Version: Non Mixer XT 1.0.6

OS: Manjaro Linux / Release: 23.1.0 / Codename: Vulcan  
Kernel: 6.6.1-1-MANJARO x86\_64

**Comment by Stazed** [comment]
I am using Manjaro with essentially your setup and I cannot create the crash. The error message you show does not contain enough information for me to tell what went wrong. Could you remove the PKGBUILD install and make a local build with debugging enabled? When the crash occurs, then send me the coredump.
For debugging:

   > mkdir build
   > cd build
   > cmake -DBuildForDebug=ON ..
   > make

You don't need to install, just run it from terminal in the build directory ./mixer/non-mixer-xt

Send me the terminal output from the debug run as well.

**Comment by BMuXBeats** [comment]
I've done all those steps, you've given me in your post.
Result: No problems - it works very fine.

It seems, tha it depends on the PKBUILD file.
It would be very nice, if this could be corrected. 
f I could, I would takin it over. But unfrtunately I'm not not really experienced to deal with PKBUILD files...

**Comment by Stazed** [comment]
It is unlikely to be the PKGBUILD since it did install the program. The PKGBUILD just executes those same commands without the -DBuildForDebug=ON. Something strange is going on with your system.  The kernel you are running is the latest bleeding edge, so you might try to downgrade and use the latest recommended 6.1.62-1.

**Comment by BMuXBeats** [comment]
I've removed the non-mixer-xt from my system - inclusive the package.
After that I've downgraded the kernel… fetched the package from github again and tried _makepkg -si_  from the ../arch directory.
No errors occured during compiling. At the end it was the same behaviour as it was with the newest kernel.
The same beahviour on my notebool under Arch Linux, by the way.

Installation without PKBUILD works in all cases without any problems, as it should.

I'm pretty sure therr's something going wrong during the installation with PKBUILD ...

**Comment by Stazed** [comment]
I have no idea what is going on then...
Is there anyone else out there having this problem?

**Comment by jean-emmanuel** [comment]
Do you have jack installed and working on your system ? Non-mixer connects to it or attempts to start it only when at least one track is created.

**Comment by Stazed** [comment]
Possibly fixed in Release 2.0.2. Please re-open if not.
