### ISSUE TITLE
Synth plugins are not available anymore in mixer strip signal chain

### ISSUE THREAD

**Issue by crshrprt** [Stazed/non-mixer-xt#22]
In the last months it seems something changed about the requirements about what plugins can be added to a signal chain inside a mixer strip.
Synth plugins in particular can't be added to a channel strip. The only synth listed is Surge XT. 
Is it because it has audio input ports?

**Comment by Stazed** [comment]
Are you following the help instructions for LV2 special cases? I sounds like you are trying to add a synth in the wrong location or have the wrong number of audio inputs. Nothing has changed about requirements on the main branch.

**Comment by crshrprt** [comment]
Where are these "help instructions for LV2 special cases"?

**Comment by crshrprt** [comment]
Yes, it works following the procedure described in _1.2.3.1.3.1. LV2 Special Cases_, thank you.
