### ISSUE TITLE
Path used to look for plugins

### ISSUE THREAD

**Issue by zigmhount** [Stazed/non-mixer-xt#23]
Hi there,

I just discovered Non-Mixer-XT yesterday and I'm very excited by the synth plugin hosting, thanks for your work! However I'm having troubles finding some of my VSTs.
Is it handling VST2 as well as VST3? if yes, in which folders is it searching for plugins? I couldn't find anything in the source code (but I did find paths to e.g. VST3 folders including `$HOME/.vst3`).

Thanks!
Zig

**Comment by Stazed** [comment]
The VST2 plugin support has not been  released yet.  Will be merged to main soon with the next release. You can try it out on the wip (work in process) branch. Use caution with the wip branch as it sometimes can be unstable.

**Comment by zigmhount** [comment]
Great, thanks for the quick response!

**Comment by zigmhount** [comment]
FWIW in case it helps others: I just realized that a simple workaround is to insert Carla as a LV2 plugin on a strip, and then insert a VST2 plugin inside Carla. Probably less risky than building the wip branch!
