### ISSUE TITLE
ATTENTION!!

### ISSUE THREAD

**Issue by Stazed** [Stazed/non-mixer-xt#26]
With release 1.3.2 a backwards breaking change was necessary to comply with the latest release of LibLO 0.32 (released 02/16/24). LibLO 0.32 has a breaking change that now requires all OSC paths to have a leading '/'. This was not required in previous releases. This change will only affect non-mixer-xt when it is used inside an NSM session. If you are using non-timeline-xt or midi-mapper-xt to control the mixer, then you can fix existing NSM projects as follows.

From inside your NSM project you will find a Non-Mixer-XT.* folder which includes a 'mappings' file. This file contains the OSC mappings for non-timeline-xt and midi-mapper-xt.  The mappings will have line(s) similar as below:
```
MIDI-Mapper-xt/control/1 |> Non-Mixer-XT.m_xt_2/strip/Unnamed/Gain/Gain%20(dB)
Non-Timeline-XT.t_xt/track/Audio/Control |> Non-Mixer-XT.m_xt_2/strip/Unnamed/Gain/Gain%20(dB)
```
You must add a leading '/' to each path as:
```
/MIDI-Mapper-xt/control/1 |> /Non-Mixer-XT.m_xt_2/strip/Unnamed/Gain/Gain%20(dB)
/Non-Timeline-XT.t_xt/track/Audio/Control |> /Non-Mixer-XT.m_xt_2/strip/Unnamed/Gain/Gain%20(dB)
```

If you are controlling the mixer with another OSC controller, then you will have to manually
add a leading '/' from the controller settings for any paths that do not have one.

**Comment by Houston4444** [comment]
If I understand well, the OSC doc has to be updated here: https://github.com/Stazed/non-mixer-xt/blob/main/OSC.md#signals-under-nsm .

**Comment by Stazed** [comment]
@Houston4444  thanks for the OSC.md tip!

**Comment by zigmhount** [comment]
Hi,
Re-building Non-Mixer-XT as per the latest commit broke the existing mappings, which was to be expected and could probably be fixed as you explained.
However I can't seem to be able to record any new mappings at all, not sure whether it may be linked to this or not.

To reproduce:
- Create a new NSM session (e.g. in RaySession)
- Add Non-Mixer-XT and add some strips
- add midi-mapper-xt
- connect midi controller to midi-mapper-xt
- Remote Control > Start recording
- The control becomes red when I click it, but never starts moving or turn green when moving a knob or fader on my controller. The mappings file remains empty.

In case it helps: In another session, I have another instance of Non-Mixer (the original, legacy) with non-midi-mapper, and if I right-click a control in Non-Mixer-XT, it shows "legacy" controls in submenus whereas the "-xt" controls as single strings, maybe this gives a clue about the cause (or it might just not be parsed correctly for displaying it in submenus):
![image](https://github.com/Stazed/non-mixer-xt/assets/58641590/a8f81199-657b-4dd3-ac63-2f55e9453e0f)

**Comment by zigmhount** [comment]
Yes, the submodule is up-to-date (and `git submodule status` confirmed the commit for nonlib).
I'm on Debian 12 (MX Linux), liblo7 version 0.31-1.

**Comment by zigmhount** [comment]
My bad, after re-pulling nonlib and re-building non-mixer-xt, it does work, details in #32 .

**Comment by grammoboy2** [comment]
Could you point to the commits/ code which fixed this? Then it could be fixed in non-mixer as well, as I think non-midimapper is failing there to.

**Comment by Stazed** [comment]
nonlib-xt:
https://github.com/Stazed/nonlib-xt/commit/f8dbfe30c2b02421d61cd85f4bf9537a8033e065

non-mixer-xt:
https://github.com/Stazed/non-mixer-xt/commit/837ed89e615b44e3e1d9d7c487a61bb519dfb73d

non-timeline-xt:
https://github.com/Stazed/non-timeline-xt/commit/3611fb17aebc884092f4337dee103b3121fa8426

**Comment by grammoboy2** [comment]
merci
