### ISSUE TITLE
fail to launch, fail to find libzix

### ISSUE THREAD

**Issue by Houston4444** [Stazed/non-mixer-xt#27]
Hi.

I am on Debian Bullseye, I installed zix from the repo given in the `readme.md` file.
When I try to launch non-mixer-xt it says:

```
/usr/local/bin/non-mixer-xt: error while loading shared libraries: libzix-0.so.0: cannot open shared object file: No such file or directory
```

however, the file is present, if I run:

```ls /usr/local/lib/x86_64-linux-gnu/|grep libzix```

the result is :

```
libzix-0.so
libzix-0.so.0
libzix-0.so.0.4.3
```

**Comment by Stazed** [comment]
Not really sure what is going on here. Seems like I ran into this somewhere before. It compiles fine then cannot find library at runtime.

Just guessing, maybe you need to run ldconfig?
```
sudo ldconfig
```

or perhaps setting LD_LIBRARY_PATH:
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/library
```

or maybe both?

**Comment by Houston4444** [comment]
Thanks.
`sudo ldconfig` make it works directly.
