### ISSUE TITLE
feature request: load a plugin state from OSC

### ISSUE THREAD

**Issue by Houston4444** [Stazed/non-mixer-xt#30]
It would be super useful (at least for me) to have a solution to load a plugin state with an OSC command. 
The more logical would be 
```/strip/[STRIP_NAME]/[MODULE_NAME]/load_state [STATE_PATH]```

Of course, if the STATE_PATH is not absolute, we should consider the project dir as the current directory.

I try to find  a solution to change state of DelayArchitect (from jpcima), which only exists in VST3 format. Because the VST3 state is not a plain text file, I can't easily script something to achieve this. And, parameter list is very long, so write something which recall all parameter values would be a PITA.

**Comment by Stazed** [comment]
Perhaps you can take this up with @jean-emmanuel the expert in all things OSC. My only interest in OSC is for automation with non-timeline-xt.

**Comment by Houston4444** [comment]
Ok, I will take a look, but of course if @jean-emmanuel can help, his help is more than welcome ;) .

**Comment by Stazed** [comment]
Gonna close this as I am not doing it...
