### ISSUE TITLE
Feature Request: Save jack connections from strip to strip in the project file

### ISSUE THREAD

**Issue by suedwestlicht** [Stazed/non-mixer-xt#37]
I discovered Non Mixer XT and use it to distribute the CPU load across multiple CPU cores, see my Qtractor HowTo https://sourceforge.net/p/qtractor/wiki/How%20To%20-%209%20Distributing%20Plugins%27%20Load%20to%20multiple%20CPU%20Cores/

It yould be great if "internal" jack connections (from mixer strip's input, output or aux to other mixer strips) would be saved in the project file.

Is this possible?

**Comment by Stazed** [comment]
Saving jack connections is one of the primary reasons to use a session manager. The mixer was originally designed to work with the NSM protocal. There are three  NSM gui front ends for NSM, new-session-manager, agordejo, and raysession.  You can likely find them in your distribution repository. They are easy to use and all are shipped with patchbay clients for connections saving. It would not make sense to add additional complexity to the mixer when there is already and easy designed alternative.

I did notice that the NSM support for Qtractor version 9.39 included with my Manjaro distribution is broken. It worked flawlessly in the past. But you can still run Qtractor outside the NSM session and run the mixer in a NSM session.

Not planning on doing this...
