### ISSUE TITLE
feature (with attached patch): eye candy by colouring dsp load meter

### ISSUE THREAD

**Issue by suedwestlicht** [Stazed/non-mixer-xt#39]
Maybe you like my patch.

[non-mixer-xt_hm-patch.txt](https://github.com/user-attachments/files/15936643/non-mixer-xt_hm-patch.txt)

One maybe stupid question: In Mixer_Strip.C there is
`dsp_load_progress->copy_tooltip( pat );`

How can I display this tooltip? Hovering over the dsp load meter doesn't show it.

**Comment by Stazed** [comment]
Hey, thanks! Definitely looks better and more useful. I Just pushed the patch to the wip branch. 
Also, the tootip did not work because of the way FLTK/NTK handled Fl_Progress class. So I added an override class to patch the handle method. It should work now...

**Comment by suedwestlicht** [comment]
Thank you. Works now. DSP load is displayed in the left bottom corner of the mixer window when hovering over the dsp load meter.
