### ISSUE TITLE
numeric input field in "gain" gets garbled when moving parameter window

### ISSUE THREAD

**Issue by suedwestlicht** [Stazed/non-mixer-xt#43]
Minimizing and maximizing restores the numeric input field. This doesn't happen with other plugins' parameter windows. See screencast.
[simplescreenrecorder-2024-09-16_11.24.57.mkv.zip](https://github.com/user-attachments/files/17010827/simplescreenrecorder-2024-09-16_11.24.57.mkv.zip)

**Comment by Stazed** [comment]
Fixed in wip branch. You will need to update the submodule.

**Comment by suedwestlicht** [comment]
Confirmed. Thank you.
