### ISSUE TITLE
Wishlist (design): move strip numbers to the colored bar above

### ISSUE THREAD

**Issue by suedwestlicht** [Stazed/non-mixer-xt#45]
The strip number in the area that shows dsp load can be misinterpreted as dsp load.

I'd prefer to see it in the colored bar above. "group dsp" in the first strip should be replaced by the strip number and moved to the colored bar since it's misleading as well when it's only displayed in the first strip.
![n](https://github.com/user-attachments/assets/328ea7e1-8ef4-4001-89b1-ab6eb1ff8801)

**Comment by Stazed** [comment]
Yes, good point, change made in wip branch.

**Comment by suedwestlicht** [comment]
Beautiful, thank you.
